### PR TITLE
remove http constraint, do not auto redirect to http if you go to https

### PR DESCRIPTION
**Pull request by peetucket**

### CODE REVIEW

**Comment by jkeck** [comment]
So are we okay with these users not getting the timeline widget on the homepage?

**Comment by jkeck** [comment]
Sorry, that last comment was me mistaken about FRDA.  No idea why we would have done this for BV.

**Comment by jkeck** [comment]
Ah, I see that was added in 1f1a98a545dc18bf8ad04c2e87c1ffb5ed1d1de2.

I would be interested to know what embed/ssl issues you were seeing, but, as this PR suggests, that shouldn't be necessary.

**Comment by peetucket** [comment]
Someone should ask that @peetucket guy why he did that commit back in 2013....

**Pull request merged**
